name: Build Mac Desktop App
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - run: RUSTFLAGS="-C linker=clang" npx tauri build
      - uses: actions/upload-artifact@v4
        with:
          name: Asfalis-Installer
          path: "**/target/bundle/dmg/*.dmg"
